export const DEFAULT_DATA = [
  {
    weight: {
      imperial: '7  -  10',
      metric: '3 - 5',
    },
    id: 'abys',
    name: 'DDAbyssinian',
    cfa_url: 'http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx',
    vetstreet_url: 'http://www.vetstreet.com/cats/abyssinian',
    vcahospitals_url:
      'https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian',
    temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
    origin: 'Egypt',
    country_codes: 'EG',
    country_code: 'EG',
    description:
      'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
    life_span: '14 - 15',
    indoor: 0,
    lap: 1,
    alt_names: '',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 3,
    dog_friendly: 4,
    energy_level: 5,
    grooming: 1,
    health_issues: 2,
    intelligence: 5,
    shedding_level: 2,
    social_needs: 5,
    stranger_friendly: 5,
    vocalisation: 1,
    experimental: 0,
    hairless: 0,
    natural: 1,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 0,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_(cat)',
    hypoallergenic: 0,
    reference_image_id: '0XYvRd7oD',
    image: {
      id: '0XYvRd7oD',
      width: 1204,
      height: 1445,
      url: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
    },
  },
  {
    weight: {
      imperial: '4 - 9',
      metric: '2 - 4',
    },
    id: 'bamb',
    name: 'Bambino',
    temperament: 'Affectionate, Lively, Friendly, Intelligent',
    origin: 'United States',
    country_codes: 'US',
    country_code: 'US',
    description:
      'The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. They love to be handled and cuddled up on the laps of their family members.',
    life_span: '12 - 14',
    indoor: 0,
    lap: 1,
    alt_names: '',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 5,
    energy_level: 5,
    grooming: 1,
    health_issues: 1,
    intelligence: 5,
    shedding_level: 1,
    social_needs: 3,
    stranger_friendly: 3,
    vocalisation: 3,
    experimental: 1,
    hairless: 1,
    natural: 0,
    rare: 0,
    rex: 0,
    suppressed_tail: 0,
    short_legs: 1,
    wikipedia_url: 'https://en.wikipedia.org/wiki/Bambino_cat',
    hypoallergenic: 0,
    reference_image_id: '5AdhMjeEu',
    image: {
      id: '5AdhMjeEu',
      width: 1296,
      height: 1030,
      url: 'https://cdn2.thecatapi.com/images/5AdhMjeEu.jpg',
    },
  },
];
